version: "3.9"
volumes:
  mysql_data:  # Define the named volume to persist MySQL data
networks:
  webtruyenchu:
services:
  webmvc:
    container_name: web-truyenchu
    image: ${DOCKER_REGISTRY-}webmvc
    build:
      context: .
      dockerfile: WebMVC/Dockerfile
    ports: 
      - 9001:80
    depends_on: 
      - mySql
    environment:
      - DB_HOST=mySql
      - DB_NAME=truyenchu
      - DB_PASS=password@12345#
      - DB_USER=root
    networks:
      - webtruyenchu
  mySql:
    image: mysql
    ports: 
      - 9002:3306
    environment:
      - MYSQL_ROOT_PASSWORD=password@12345#
    volumes:
      - mysql_data:/var/lib/mysql  # Gắn volume với thư mục chứa dữ liệu MySQL\
      - ./init-database.sql:/docker-entrypoint-initdb.d/init-database.sql:ro
    networks:
      - webtruyenchu